# Generated by Django 4.0.6 on 2022-08-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_featured_story_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Sories categories'},
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='author',
            field=models.CharField(default='JLH-Uganda, Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
    ]
