# Generated by Django 4.0.6 on 2022-08-15 03:51

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='body',
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='page_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='GalleryPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('tag', models.CharField(blank=True, help_text='Image Tag, eg ALP, CPTA, WETP, etc.', max_length=250)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.gallerypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
