# Generated by Django 4.0.6 on 2022-08-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0002_remove_gallerypage_body_gallerypage_page_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatepage',
            name='hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
