# Generated by Django 4.0.6 on 2022-08-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donatepage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='annual_beneficiary_count',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
